import { CategoryBoard } from "./definitions";

export const categoryList = [
  { title: "전체", path: "all" },
  { title: "공지", path: "inform" },
  { title: "잡담", path: "talk" },
  { title: "유머", path: "humor" },
  { title: "자랑", path: "goodItem" },
  { title: "질문", path: "question" },
];
export const userInfo = {
  profileImg: "/placeholder-noavatar32.svg",
  isLogin: true,
};
export const boardList: CategoryBoard[] = [
  {
    commentNum: 32,
    boardId: 24,
    categoryPath: "all",
    createdAt: new Date(Date.now() - 6048000000),
    img: "/baseBoardImg.png",
    category: "공지",
    content: "내용",
    title: "타이틀",
    writer: "작성자",
    writerId: 23,
  },
  {
    commentNum: 32,
    boardId: 24,
    categoryPath: "all",
    createdAt: new Date(Date.now() - 6048000000),
    img: "/baseBoardImg.png",
    category: "공지",
    content: "내용",
    title: "타이틀",
    writer: "작성자",
    writerId: 23,
  },
  {
    commentNum: 32,
    boardId: 24,
    categoryPath: "all",
    createdAt: new Date(Date.now() - 6048000000),
    img: "/baseBoardImg.png",
    category: "공지",
    content: "내용",
    title: "타이틀",
    writer: "작성자",
    writerId: 23,
  },
  {
    commentNum: 32,
    boardId: 24,
    categoryPath: "all",
    createdAt: new Date(Date.now() - 6048000000),
    img: "/baseBoardImg.png",
    category: "공지",
    content: "내용",
    title: "타이틀",
    writer: "작성자",
    writerId: 23,
  },
  {
    commentNum: 32,
    boardId: 24,
    categoryPath: "all",
    createdAt: new Date(Date.now() - 6048000000),
    img: "/baseBoardImg.png",
    category: "공지",
    content: "내용",
    title: "타이틀",
    writer: "작성자",
    writerId: 23,
  },
];
export const categoryInformBoard: CategoryBoard = {
  isTop: true,
  commentNum: 32,
  boardId: 24,
  categoryPath: "all",
  createdAt: new Date(Date.now() - 6048000000),
  img: "/baseBoardImg.png",
  category: "공지",
  content: "내용",
  title: "타이틀",
  writer: "작성자",
  writerId: 23,
};
export const countBoard = 132;
