import {
  CategoryDetailData,
  CmtListData,
  ReasonListData,
  UserInfoData,
  CategoryListData,
  BoardListData,
  CategoryInformBoard,
  BoardDetailData,
} from "./definitions";

export const categoryListData: CategoryListData = {
  categories: [
    {
      id: 1,
      name: "전체",
      path: "all",
      img: "/baseBoardImg.png",
      description: "아아",
    },
    {
      id: 2,
      name: "공지",
      path: "inform",
      img: "/baseBoardImg.png",
      description: "나나",
    },
    {
      id: 3,
      name: "잡담",
      path: "talk",
      img: "/baseBoardImg.png",
      description: "dkdk",
    },
    {
      id: 4,
      name: "유머",
      path: "humor",
      img: "/baseBoardImg.png",
      description: "kdkd",
    },
    {
      id: 5,
      name: "자랑",
      path: "goodItem",
      img: "/baseBoardImg.png",
      description: "카",
    },
    {
      id: 6,
      name: "질문",
      path: "question",
      img: "/baseBoardImg.png",
      description: "다",
    },
  ],
};
export const userInfoData: UserInfoData = {
  userInfo: {
    profileImg: "/placeholder-noavatar32.svg",
    id: 3,
    nick: "나야나",
    email: "rk@naver.com",
    cmtCnt: 44,
    boardsCnt: 22,
    like: 312,
    dislike: 222,
    createdAt: new Date(Date.now() - 3000000),
  },
  // userInfo: null,
};

export const boardListData: BoardListData = {
  boardCnt: 4,
  boardList: [
    {
      cmtCnt: 32,
      id: 24,
      categoryPath: "all",
      createdAt: new Date(Date.now() - 6048000000),
      img: "/baseBoardImg.png",
      category: "공지",
      title: "타이틀",
      writer: "작성자",
      writerId: 23,
      isUpdated: true,
      score: 4.5,
      scoreUserCnt: 55,
      description: "아자차카타파하",
    },
    {
      cmtCnt: 32,
      id: 24,
      categoryPath: "all",
      createdAt: new Date(Date.now() - 6048000000),
      img: "/baseBoardImg.png",
      category: "공지",
      title: "타이틀",
      writer: "작성자",
      writerId: 23,
      isUpdated: true,
      score: 4.5,
      scoreUserCnt: 55,
      description: "아자차카타파하",
    },
    {
      cmtCnt: 32,
      id: 24,
      categoryPath: "all",
      createdAt: new Date(Date.now() - 6048000000),
      img: "/baseBoardImg.png",
      category: "공지",
      title: "타이틀",
      writer: "작성자",
      writerId: 23,
      isUpdated: true,
      score: 4.5,
      scoreUserCnt: 55,
      description: "아자차카타파하",
    },
    {
      cmtCnt: 32,
      id: 24,
      categoryPath: "all",
      createdAt: new Date(Date.now() - 6048000000),
      img: "/baseBoardImg.png",
      category: "공지",
      title: "타이틀",
      writer: "작성자",
      writerId: 23,
      isUpdated: true,
      score: 4.5,
      scoreUserCnt: 55,
      description: "아자차카타파하",
    },
  ],
};
export const categoryInformBoard: CategoryInformBoard = {
  cmtCnt: 32,
  id: 24,
  createdAt: new Date(Date.now() - 6048000000),
  img: "/baseBoardImg.png",
  description: "아자차카타파하아자차카",
  title: "타이틀",
  writer: "작성자",
  writerId: 23,
};
export const categoryDetailData: CategoryDetailData = {
  path: "/humor",
  name: "유머",
  img: "/baseBoardImg.png",
  description: "아아아",
  cmtPlaceholder: "댓글 placeholder입니다~",
  titlePlaceholder: "게시글 제목 placeholder입니다~",
  descriptionPlaceholder: "게시글  설명글 placeholder입니다~",
  contentPlaceholder: "게시글 내용 placeholder입니다~",
  boardCnt: 32,
  rules: ["아아", "이런곳에서"],
  informBoard: categoryInformBoard,
};
export const currentBoardData: BoardDetailData = {
  category: "유머",
  categoryPath: "humor",
  title: "이타치가 왜 강한줄 아나?",
  cmtCnt: 32,
  id: 24,
  createdAt: new Date(Date.now() - 6048000000),
  img: "/baseBoardImg.png",
  content: "내용",
  writer: "작성자",
  writerId: 23,
  score: 4.3,
  scoreUserCnt: 32,
  isGiveScore: false,
  isDidReport: false,
  description: "아자차카타파하",
  isUpdated: true,
};
export const boardReportReasonListData: ReasonListData = {
  reasonList: [
    { id: 1, title: "그냥 심심풀이" },
    { id: 2, title: "매너가 나쁩니다", description: "ㅇㅇ." },
    { id: 3, title: "그냥 싫습니다", description: "그럴수도 있죠" },
  ],
};
export const cmtReportReasonListData: ReasonListData = {
  reasonList: [
    { id: 1, title: "그냥 심심풀이" },
    { id: 2, title: "매너가 나쁩니다", description: "ㅇㅇ." },
    { id: 3, title: "그냥 싫습니다", description: "그럴수도 있죠" },
  ],
};

export const cmtData: CmtListData = {
  cmtList: [
    {
      id: 1,
      writer: "나야나",
      writerId: 3,
      createdAt: new Date(50000000000),
      content:
        '<div><div style="width: 10rem; height: 10rem;"><img src="/facebookLogo.svg" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;">(*수정됨)</span><span class="cmtTextContent">아아아</span></div></div>',
      like: 3,
      dislike: 32,
      isDoLike: true,
      isDoDislike: false,
      isDidReport: false,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      isDeleted: false,
      containCmt: [
        {
          id: 2,
          writer: "샤아",
          writerId: 4,
          createdAt: new Date(Date.now() - 10000000),
          content:
            '<div><div style="width: 10rem; height: 10rem;"><img src="/baseBoardImg.png" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;">(*수정됨)</span><span class="cmtTextContent">왜그러는데</span></div></div>',
          like: 12,
          dislike: 42,
          isDoLike: false,
          isDoDislike: true,
          isDidReport: false,
          boardId: 24,
          categoryPath: "/humor",
          category: "유머",
          boardTitle: "이타치가 왜 강한줄 아나?",
          writerProfile: "/baseBoardImg.png",
          replyId: 1,
          replyUserId: 3,
          replyUser: "나야나",
          isDeleted: false,
          containCmt: [
            {
              id: 3,
              writer: "나야나",
              writerId: 3,
              createdAt: new Date(Date.now() - 10000000),
              content:
                '<div><div><span style="color: #042552;font-size: 0.75rem;">(*수정됨)</span><span class="cmtTextContent">솔직하게 말할래 그만하자고 헷갈리는 이 관계 정리하자고 오늘부터 </span></div></div>',
              like: 30,
              dislike: 32,
              isDoLike: true,
              isDoDislike: false,
              isDidReport: true,
              boardId: 24,
              categoryPath: "/humor",
              category: "유머",
              boardTitle: "이타치가 왜 강한줄 아나?",
              writerProfile: "/baseBoardImg.png",
              replyId: 2,
              replyUserId: 4,
              replyUser: "샤아",
              isDeleted: false,
            },
            {
              id: 5,
              writer: "나야나",
              writerId: 3,
              createdAt: new Date(Date.now() - 10000000),
              content:
                '<div><div><span style="color: #042552;font-size: 0.75rem;">(*수정됨)</span><span class="cmtTextContent">솔직하게 말할래 그만하자고 헷갈리는 이 관계 정리하자고 오늘부터 </span></div></div>',
              like: 30,
              dislike: 32,
              isDoLike: true,
              isDoDislike: false,
              isDidReport: true,
              boardId: 24,
              categoryPath: "/humor",
              category: "유머",
              boardTitle: "이타치가 왜 강한줄 아나?",
              writerProfile: "/baseBoardImg.png",
              replyId: 2,
              replyUserId: 4,
              replyUser: "샤아",
              isDeleted: false,
            },
            {
              id: 6,
              writer: "나야나",
              writerId: 3,
              createdAt: new Date(Date.now() - 10000000),
              content:
                '<div><div><span style="color: #042552;font-size: 0.75rem;">(*수정됨)</span><span class="cmtTextContent">솔직하게 말할래 그만하자고 헷갈리는 이 관계 정리하자고 오늘부터 </span></div></div>',
              like: 10,
              dislike: 32,
              isDoLike: true,
              isDoDislike: false,
              isDidReport: true,
              boardId: 24,
              categoryPath: "/humor",
              category: "유머",
              boardTitle: "이타치가 왜 강한줄 아나?",
              writerProfile: "/baseBoardImg.png",
              replyId: 2,
              replyUserId: 4,
              replyUser: "샤아",
              isDeleted: false,
            },
          ],
        },
      ],
    },

    {
      id: 4,
      writer: "누군가가쓰는",
      writerId: 5,
      createdAt: new Date(500000000000),
      content:
        '<div><div style="width: 10rem; height: 10rem;"><img src="/search.svg" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;"></span><span class="cmtTextContent">왜일까 잘난듯한 소리가들려</span></div></div>',
      like: 21,
      dislike: 0,
      isDoLike: false,
      isDoDislike: false,
      isDidReport: false,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      isDeleted: false,
    },
    {
      id: 7,
      writer: "누군가가쓰는",
      writerId: 5,
      createdAt: new Date(500000000000),
      content:
        '<div><div style="width: 10rem; height: 10rem;"><img src="/search.svg" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;"></span><span class="cmtTextContent">왜일까 잘난듯한 소리가들려</span></div></div>',
      like: 21,
      dislike: 0,
      isDoLike: false,
      isDoDislike: false,
      isDidReport: false,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      isDeleted: false,
    },
    {
      id: 8,
      writer: "누군가가쓰는",
      writerId: 5,
      createdAt: new Date(500000000000),
      content:
        '<div><div style="width: 10rem; height: 10rem;"><img src="/search.svg" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;"></span><span class="cmtTextContent">왜일까 잘난듯한 소리가들려</span></div></div>',
      like: 21,
      dislike: 0,
      isDoLike: false,
      isDoDislike: false,
      isDidReport: false,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      isDeleted: false,
    },
    {
      id: 9,
      writer: "누군가가쓰는",
      writerId: 5,
      createdAt: new Date(500000000000),
      content:
        '<div><div style="width: 10rem; height: 10rem;"><img src="/search.svg" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;"></span><span class="cmtTextContent">왜일까 잘난듯한 소리가들려</span></div></div>',
      like: 21,
      dislike: 0,
      isDoLike: false,
      isDoDislike: false,
      isDidReport: false,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      isDeleted: false,
    },
    {
      id: 10,
      writer: "누군가가쓰는",
      writerId: 5,
      createdAt: new Date(500000000000),
      content:
        '<div><div style="width: 10rem; height: 10rem;"><img src="/search.svg" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;"></span><span class="cmtTextContent">왜일까 잘난듯한 소리가들려</span></div></div>',
      like: 21,
      dislike: 0,
      isDoLike: false,
      isDoDislike: false,
      isDidReport: false,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      isDeleted: false,
    },
  ],
  cmtCnt: 6,
};

export const mycmtData: CmtListData = {
  cmtList: [
    {
      id: 1,
      writer: "나야나",
      writerId: 3,
      createdAt: new Date(50000000000),
      content:
        '<div><div style="width: 10rem; height: 10rem;"><img src="/facebookLogo.svg" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;">(*수정됨)</span><span class="cmtTextContent">아아아</span></div></div>',
      like: 3,
      dislike: 32,
      isDoLike: true,
      isDoDislike: false,
      isDidReport: false,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      isDeleted: false,
    },

    {
      id: 4,
      writer: "나야나",
      writerId: 3,
      createdAt: new Date(500000000000),
      content:
        '<div><div style="width: 10rem; height: 10rem;"><img src="/search.svg" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;"></span><span class="cmtTextContent">왜일까 잘난듯한 소리가들려</span></div></div>',
      like: 21,
      dislike: 0,
      isDoLike: false,
      isDoDislike: false,
      isDidReport: false,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      isDeleted: false,
    },
    {
      id: 7,
      writer: "나야나",
      writerId: 3,
      createdAt: new Date(500000000000),
      content:
        '<div><div style="width: 10rem; height: 10rem;"><img src="/search.svg" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;"></span><span class="cmtTextContent">왜일까 잘난듯한 소리가들려</span></div></div>',
      like: 21,
      dislike: 0,
      isDoLike: false,
      isDoDislike: false,
      isDidReport: false,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      isDeleted: false,
    },
    {
      id: 8,
      writer: "나야나",
      writerId: 3,
      createdAt: new Date(500000000000),
      content:
        '<div><div style="width: 10rem; height: 10rem;"><img src="/search.svg" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;"></span><span class="cmtTextContent">왜일까 잘난듯한 소리가들려</span></div></div>',
      like: 21,
      dislike: 0,
      isDoLike: false,
      isDoDislike: false,
      isDidReport: false,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      isDeleted: false,
    },
    {
      id: 9,
      writer: "나야나",
      writerId: 3,
      createdAt: new Date(500000000000),
      content:
        '<div><div style="width: 10rem; height: 10rem;"><img src="/search.svg" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;"></span><span class="cmtTextContent">왜일까 잘난듯한 소리가들려</span></div></div>',
      like: 21,
      dislike: 0,
      isDoLike: false,
      isDoDislike: false,
      isDidReport: false,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      isDeleted: false,
    },
    {
      id: 10,
      writer: "나야나",
      writerId: 3,
      createdAt: new Date(500000000000),
      content:
        '<div><div style="width: 10rem; height: 10rem;"><img src="/search.svg" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;"></span><span class="cmtTextContent">왜일까 잘난듯한 소리가들려</span></div></div>',
      like: 21,
      dislike: 0,
      isDoLike: false,
      isDoDislike: false,
      isDidReport: false,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      isDeleted: false,
    },
    {
      id: 3,
      writer: "나야나",
      writerId: 3,
      createdAt: new Date(Date.now() - 10000000),
      content:
        '<div><div><span style="color: #042552;font-size: 0.75rem;">(*수정됨)</span><span class="cmtTextContent">솔직하게 말할래 그만하자고 헷갈리는 이 관계 정리하자고 오늘부터 </span></div></div>',
      like: 30,
      dislike: 32,
      isDoLike: true,
      isDoDislike: false,
      isDidReport: true,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      replyId: 2,
      replyUserId: 4,
      replyUser: "샤아",
      isDeleted: false,
    },
    {
      id: 5,
      writer: "나야나",
      writerId: 3,
      createdAt: new Date(Date.now() - 10000000),
      content:
        '<div><div><span style="color: #042552;font-size: 0.75rem;">(*수정됨)</span><span class="cmtTextContent">솔직하게 말할래 그만하자고 헷갈리는 이 관계 정리하자고 오늘부터 </span></div></div>',
      like: 30,
      dislike: 32,
      isDoLike: true,
      isDoDislike: false,
      isDidReport: true,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      replyId: 2,
      replyUserId: 4,
      replyUser: "샤아",
      isDeleted: false,
    },
    {
      id: 6,
      writer: "나야나",
      writerId: 3,
      createdAt: new Date(Date.now() - 10000000),
      content:
        '<div><div><span style="color: #042552;font-size: 0.75rem;">(*수정됨)</span><span class="cmtTextContent">솔직하게 말할래 그만하자고 헷갈리는 이 관계 정리하자고 오늘부터 </span></div></div>',
      like: 10,
      dislike: 32,
      isDoLike: true,
      isDoDislike: false,
      isDidReport: true,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      replyId: 2,
      replyUserId: 4,
      replyUser: "샤아",
      isDeleted: false,
    },
    {
      id: 2,
      writer: "나야나",
      writerId: 3,
      createdAt: new Date(Date.now() - 10000000),
      content:
        '<div><div style="width: 10rem; height: 10rem;"><img src="/baseBoardImg.png" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;">(*수정됨)</span><span class="cmtTextContent">왜그러는데</span></div></div>',
      like: 12,
      dislike: 42,
      isDoLike: false,
      isDoDislike: true,
      isDidReport: false,
      boardId: 24,
      categoryPath: "/humor",
      category: "유머",
      boardTitle: "이타치가 왜 강한줄 아나?",
      writerProfile: "/baseBoardImg.png",
      replyId: 1,
      replyUserId: 3,
      replyUser: "나야나",
      isDeleted: false,
    },
  ],
  cmtCnt: 10,
};
//'<div><div style="width: 10rem; height: 10rem;"><img src="/baseBoardImg.png" style="width: 100%; height: 100%;"></div><div><span style="color: #042552;font-size: 0.75rem;">(*수정됨)</span>아아아</div></div>';

export const myBoardListData: BoardListData = {
  boardCnt: 4,
  boardList: [
    {
      cmtCnt: 32,
      id: 24,
      categoryPath: "all",
      createdAt: new Date(Date.now() - 6048000000),
      img: "/baseBoardImg.png",
      category: "공지",
      title: "타이틀",
      writer: "나야나",
      writerId: 3,
      isUpdated: true,
      score: 4.5,
      scoreUserCnt: 55,
      description: "아자차카타파하",
    },
    {
      cmtCnt: 32,
      id: 24,
      categoryPath: "all",
      createdAt: new Date(Date.now() - 6048000000),
      img: "/baseBoardImg.png",
      category: "공지",
      title: "타이틀",
      writer: "나야나",
      writerId: 3,
      isUpdated: true,
      score: 4.5,
      scoreUserCnt: 55,
      description: "아자차카타파하",
    },
    {
      cmtCnt: 32,
      id: 24,
      categoryPath: "all",
      createdAt: new Date(Date.now() - 6048000000),
      img: "/baseBoardImg.png",
      category: "공지",
      title: "타이틀",
      writer: "나야나",
      writerId: 3,
      isUpdated: true,
      score: 4.5,
      scoreUserCnt: 55,
      description: "아자차카타파하",
    },
    {
      cmtCnt: 32,
      id: 24,
      categoryPath: "all",
      createdAt: new Date(Date.now() - 6048000000),
      img: "/baseBoardImg.png",
      category: "공지",
      title: "타이틀",
      writer: "나야나",
      writerId: 3,
      isUpdated: true,
      score: 4.5,
      scoreUserCnt: 55,
      description: "아자차카타파하",
    },
  ],
};
